# Github actions makes it hard to test new workflow_dispatch workflows
# because the workflow definition needs to be in the main branch for it to
# appear in the actions tab.
# This workflow is meant to be used during development so we don't have to check
# in a new file to master every time we need to add a new workflow.

name: Placeholder workflow
on:
  workflow_dispatch:

jobs:
  build:
    name: Noop
    runs-on:
      - self-hosted
      - Linux
      - X64
      - sre
    steps:
      - run: echo "I'm a placeholder"
